// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartShoppingAssistant.DataAccess;

#nullable disable

namespace SmartShoppingAssistant.DataAccess.Migrations
{
    [DbContext(typeof(SmartShoppingAssistantDbContext))]
    [Migration("20260512102518_updatedb")]
    partial class updatedb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Băuturi răcoritoare și sucuri",
                            Name = "Băuturi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gustări și dulciuri",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Produse lactate",
                            Name = "Lactate"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pâine, cozonaci și produse de patiserie",
                            Name = "Panificație"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Legume și fructe proaspete",
                            Name = "Legume și Fructe"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Produse din carne și mezeluri",
                            Name = "Carne și Mezeluri"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Produse de igienă și cosmetice",
                            Name = "Îngrijire Personală"
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Băutură carbogazoasă",
                            Name = "Coca Cola 500ml",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Băutură carbogazoasă",
                            Name = "Pepsi 500ml",
                            Price = 5.49m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chipsuri cu sare",
                            Name = "Lay's Sare",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Iaurt 400g",
                            Name = "Iaurt natural",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Băutură carbogazoasă cu aromă de portocale",
                            Name = "Fanta Portocale 500ml",
                            Price = 5.49m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Băutură carbogazoasă cu lămâie și lime",
                            Name = "Sprite 500ml",
                            Price = 5.49m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Apă minerală plată",
                            Name = "Apă Plată Bucovina 2L",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Chipsuri crocante în tub",
                            Name = "Pringles Original 165g",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Chipsuri de porumb cu aromă de brânză",
                            Name = "Doritos Nacho Cheese 150g",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ciocolată cu lapte alpin",
                            Name = "Milka Lapte Alpin 100g",
                            Price = 6.49m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Lapte proaspăt de vacă 3.5% grăsime",
                            Name = "Lapte Zuzu 1L",
                            Price = 7.29m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Brânză telemea de vacă",
                            Name = "Brânză Telemea 400g",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Smântână pentru gătit și salate",
                            Name = "Smântână 20% 400g",
                            Price = 8.49m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Pâine albă moale, feliată",
                            Name = "Pâine Albă Feliată 500g",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Croissant cu unt, proaspăt",
                            Name = "Croissant Simplu",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Mere românești, soiul Ionatan",
                            Name = "Mere Ionatan 1kg",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Roșii cherry proaspete",
                            Name = "Roșii Cherry 500g",
                            Price = 8.99m
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Reward")
                        .HasColumnType("int");

                    b.Property<int>("RewardValue")
                        .HasColumnType("int");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Cumpără 5 Coca-Cola, primești 1 gratis",
                            ProductId = 1,
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 5m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "10% reducere la comenzi peste 100 RON",
                            Reward = 1,
                            RewardValue = 10,
                            Threshold = 100.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Cumpără 3 Snacks-uri, primești 1 gratis",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 3m,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Cumpără 2 Pepsi, primești 1 gratis",
                            ProductId = 2,
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 2m,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Cumpără 4 lactate, primești 1 gratis",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 4m,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "20% reducere la comenzi peste 200 RON",
                            Reward = 1,
                            RewardValue = 20,
                            Threshold = 200.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Cumpără 3 Ape Plată, primești 1 gratis",
                            ProductId = 7,
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 3m,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "5% reducere la comenzi peste 50 RON",
                            Reward = 1,
                            RewardValue = 5,
                            Threshold = 50.00m,
                            Type = 1
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.CartItem", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithOne("cartItem")
                        .HasForeignKey("SmartShoppingAssistant.DataAccess.Entities.CartItem", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.ProductCategory", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Promotion", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Category", "Category")
                        .WithMany("Promotions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Product", b =>
                {
                    b.Navigation("Promotions");

                    b.Navigation("cartItem");
                });
#pragma warning restore 612, 618
        }
    }
}
